# Generated by Django 3.1.3 on 2021-03-31 16:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('contenuto', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pagine',
        ),
    ]
